# Generated by Django 3.2.4 on 2022-10-05 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[home_app.validators.empty])),
                ('maxpoints', models.IntegerField(default=50)),
                ('owner', models.CharField(max_length=100)),
                ('shared', models.BooleanField(default=False)),
                ('stats', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharedgroups', models.ManyToManyField(related_name='sharedgroups', to='home_app.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stats', models.JSONField(default={'hands': [], 'moonshots': 0, 'placings': [], 'queens': 0})),
                ('hands', models.TextField(default='')),
                ('queens', models.IntegerField(default=0)),
                ('moonshots', models.IntegerField(default=0)),
                ('placings', models.TextField(default='')),
                ('group', models.ManyToManyField(to='home_app.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('complete', models.BooleanField(default=False)),
                ('results', models.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.group')),
            ],
        ),
    ]
