# Generated by Django 3.2.4 on 2022-10-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='hands',
        ),
        migrations.RemoveField(
            model_name='person',
            name='moonshots',
        ),
        migrations.RemoveField(
            model_name='person',
            name='placings',
        ),
        migrations.RemoveField(
            model_name='person',
            name='queens',
        ),
        migrations.AlterField(
            model_name='game',
            name='results',
            field=models.JSONField(verbose_name='[]'),
        ),
        migrations.AlterField(
            model_name='group',
            name='stats',
            field=models.JSONField(verbose_name='[]'),
        ),
        migrations.AlterField(
            model_name='person',
            name='stats',
            field=models.JSONField(default='{}'),
        ),
    ]
