# Generated by Django 3.2.4 on 2022-10-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20221004_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='results',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='stats',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='stats',
            field=models.JSONField(),
        ),
    ]
