# Generated by Django 3.2.4 on 2022-10-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_remove_game_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rotation',
            field=models.JSONField(default=True),
            preserve_default=False,
        ),
    ]
