# Generated by Django 3.2.4 on 2022-11-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_group_rotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sharedgroups',
            field=models.ManyToManyField(related_name='sharedUsers', to='home_app.group'),
        ),
    ]
